version: '3.8'

services:
  php-laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel
    volumes:
      - ./src:/var/www
    expose:
      - "9000"
    networks:
      - app-network
    depends_on:
      - mysql-laravel

  nginx-laravel:
    image: nginx:alpine
    container_name: nginx-laravel
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - php-laravel

  mysql-laravel:
    image: mysql:8.0
    container_name: mysql-laravel
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
